### ISSUE TITLE
Why is main file from src and not from dist?

### ISSUE THREAD

**Issue by lhguerra** [fnando/cpf#3]
This is a section of the `package.json` file in the module downloaded from npm.

```
"name": "@fnando/cpf",
  "version": "0.1.0",
  "description": "Validate, generate and format CPF numbers",
  "main": "src/cpf.js",
```

This causes an error when using node:
```
node_modules/@fnando/cpf/src/cpf.js:19
export function verifierDigit(numbers) {
^^^^^^

SyntaxError: Unexpected token export
```

**Comment by raphaklaus** [comment]
The maintainer seems to forget publishing to NPM registry this commit: 0b90814581a9f2bd947c5b9dade59e5c1fc518c7
