### ISSUE TITLE
Doesn't work in IE 11 and IE10

### ISSUE THREAD

**Issue by adrianotosta** [fnando/cpf#4]
I have been using this repo into a vuejs application, in chrome, firefox and edge it has been working fine. But, in IE 11 and IE10 it hasn't been working.

**Comment by emartini** [comment]
You can polyfill `Array.includes`
https://github.com/fnando/cpf/blob/master/src/cpf.js#L104

**Comment by wkrueger** [comment]
sacanagem colocar um Array.includes em uma lib de uso geral...

**Comment by pauladiniz** [comment]
Segue não funcionando no IE11, o jeito é o polyfill, mas ainda sim, complicado.
